### ISSUE TITLE
Cannot find symbol error

### ISSUE THREAD

**Issue by willnix86** [dpa99c/cordova-plugin-firebase#11]
**Describe the bug**
Installing on Android after following your instructions, I receive the following error:

````javascript

> Task :app:compileDebugJavaWithJavac FAILED

..../mobile-app/platforms/android/app/src/main/java/org/apache/cordova/firebase/FirebasePlugin.java:893: error: cannot find symbol
                        myTrace.incrementMetric(counterNamed, 1);
                               ^
  symbol:   method incrementMetric(String,int)
  location: variable myTrace of type Trace
..../mobile-app/platforms/android/app/src/main/java/org/apache/cordova/firebase/FirebasePluginMessagingService.java:49: error: method does not override or implement a method from a supertype
    @Override
    ^
....mobile-app/platforms/android/app/src/main/java/org/apache/cordova/firebase/FirebasePluginMessagingService.java:51: error: cannot find symbol
        super.onNewToken(refreshedToken);
             ^
  symbol: method onNewToken(String)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.

````

Any thoughts?

**Comment by dpa99c** [comment]
It looks to me as if an older version of the Firebase SDK has been pulled into your build causing [my changes to update the plugin for the new Firebase SDK API](https://github.com/dpa99c/cordova-plugin-firebase/commit/143f450894e89ff7d77d31197738386d5bea2a16) to break your build.

Please post the `dependencies` of `platforms/android/app/build.gradle` so I can see what version is being pulled in - it should look somethine like this:

        // SUB-PROJECT DEPENDENCIES START
        implementation(project(path: ":CordovaLib"))
        implementation "com.google.android.gms:play-services-tagmanager:17.0.0"
        implementation "com.google.firebase:firebase-core:17.0.0"
        implementation "com.google.firebase:firebase-messaging:19.0.0"
        implementation "com.google.firebase:firebase-config:18.0.0"
        implementation "com.google.firebase:firebase-perf:18.0.0"
        implementation "com.google.firebase:firebase-auth:18.0.0"
        implementation "com.crashlytics.sdk.android:crashlytics:2.9.8"
        implementation "me.leolin:ShortcutBadger:1.1.22"
        // SUB-PROJECT DEPENDENCIES END

Also try these test case commands in your environment and confirm the result:

    cordova create test io.cordova.firebase.test && cd test
    cordova plugin add cordova-plugin-firebasex

    curl https://raw.githubusercontent.com/dpa99c/cordova-plugin-firebase-test/master/www/google-services.json -o google-services.json
    cordova platform add android@latest
    cordova build android

**Comment by willnix86** [comment]
Ok, so looks like Cordova now builds it successfully but we have another issue.

First, the fix to make it build was having firebase-gradle-plugin installed, so I removed that and made sure play-services-gradle was set to 17.0.0+

But now we have another problem. When I try to run/build the Android project in Android studio I get the following error:

````javascript
ERROR: Manifest merger failed : uses-sdk:minSdkVersion 1 cannot be smaller than version 19 declared in library [__tested_artifact__::CordovaLib] /Users/wnixon/br-projects/analytics-dhs/mobile-app/platforms/android/CordovaLib/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 1
	Suggestion: use a compatible library with a minSdk of at most 1,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="org.apache.cordova" to force usage (may lead to runtime failures)
````

I have the following two preferences set in my config.xml, so not sure why I'm getting this issue?

<preference name="android-minSdkVersion" value="21"/>
<preference name="android-targetSdkVersion" value="28"/>

**Comment by dpa99c** [comment]
Looks like the minSDK has been set to `1` somehow but `cordova-android@8` has a min SDK requirement of 19.
You can a look at your `.gradle` configs and `AndroidManifest.xml` to check where this has happened.

I would try `rm -Rf platforms/android/ && cordova platform add android` to re-add the platform.
If it occurs again after this, look at the plugins in your `plugins/` directory for a cause.

Closing this as an issue though because this plugin is not directly responsible for that error (as can be seen from the test case).

**Comment by willnix86** [comment]
Thanks @dpa99c - I'll look into that further!
