### ISSUE TITLE
Android working fine now but issues with Pods for iOS

### ISSUE THREAD

**Issue by REPTILEHAUS** [dpa99c/cordova-plugin-firebase#15]
Nice work getting this launched, solved my issues with android... however stopping that leak with my finger spawned another leak :D I cant build for iOS now

This is my build script. nothing major just clears emulator caches, then copys env and builds then removes prev ios platform and adds new one
```
#!/bin/bash
# ionic build
/usr/bin/xcrun simctl erase all
node scripts/copy-environment.js --env prod && ionic cordova build ios --prod --release
ionic cordova platform rm ios
cordova platform add ios@5.0.0
```

Error occurs during running of script

```
    build-release.xcconfig line 29: Unable to find included file "Pods/Target Support Files/Pods-AppName/Pods-AppName.release.xcconfig"** BUILD FAILED **


The following build commands failed:
	CompileC /Users/myname/Library/Developer/Xcode/DerivedData/AppName-bucwxhodaumzfehhbvriuiyugncg/Build/Intermediates.noindex/Appname.build/Release-iphonesimulator/Appname.build/Objects-normal/x86_64/AppDelegate+FirebasePlugin.o Appname/Plugins/cordova-plugin-firebasex/AppDelegate+FirebasePlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
CordovaError: Promise rejected with non-error: 'Error code 65 for command: xcodebuild with args: -xcconfig,/Applications/Apps/appname/app/platforms/ios/cordova/build-release.xcconfig,-workspace,AppName.xcworkspace,-scheme,AppName,-configuration,Release,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone Xʀ,build,CONFIGURATION_BUILD_DIR=/Applications/Apps/appname/app/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Applications/Apps/appname/app/platforms/ios/build/sharedpch,-UseModernBuildSystem=0'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:30:15)
```

Also during running of script

```
Checking cordova-plugin-device for pods.
Checking cordova-plugin-file for pods.
Checking cordova-plugin-firebasex for pods.
cordova-plugin-firebasex requires pod: Firebase/Core
cordova-plugin-firebasex requires pod: Firebase/Auth
cordova-plugin-firebasex requires pod: Firebase/Messaging
cordova-plugin-firebasex requires pod: Firebase/Performance
cordova-plugin-firebasex requires pod: Firebase/RemoteConfig
cordova-plugin-firebasex requires pod: Fabric
cordova-plugin-firebasex requires pod: Crashlytics
Checking cordova-plugin-inappbrowser for pods.
Checking cordova-plugin-ionic-keyboard for pods.
Checking cordova-plugin-ionic-webview for pods.
Checking cordova-plugin-splashscreen for pods.
```

It seems to complete compiling without error but when i open the project in xcode and try to build it there for a device 
I get these errors 

```
Showing Recent Messages
:-1: /Applications/Apps/AppName/app/platforms/ios/cordova/build-debug.xcconfig:34: could not find included file 'Pods/Target Support Files/Pods-AppName/Pods-AppName.debug.xcconfig' in search paths (in target 'AppName')

```

**Comment by dpa99c** [comment]
Did you open `YourProject.xcworkspace` or `YourProject.xcodeproj` in Xcode?
(you need to open `YourProject.xcworkspace` so both your Cordova app project and the Pods project will be loaded into Xcode.)

Please try cloning and building [this example project](https://github.com/dpa99c/cordova-plugin-firebase-test) as a reference.

**Comment by REPTILEHAUS** [comment]
I got it running by installing cocoapods, pods setup, pods install in /platform/ios/ 

It wasnt necessary before though, anyway its up and running now for both platforms so thats the main thing. Great fix, you should really consider taking this over as the other maintainers dont seem to care at all

**Comment by dpa99c** [comment]
I already have Cocopods installed for native dev purposes so didn't even think about it as a peer dependency. I should update the documentation for this fork to say that global cocopods installation is a prerequisite. Therefore I'll leave this issue open to remind me to do that.

**Comment by b-d-m-p** [comment]
I'm still having the same issue. Not able to fix it with the suggestions.

**Comment by michelepatrassi** [comment]
@b-d-m-p did you followed these steps?
- https://github.com/dpa99c/cordova-plugin-firebasex#cocoapods
- https://github.com/dpa99c/cordova-plugin-firebasex#cocoapods

I also added `sudo gem update cocoapods` before those
