### ISSUE TITLE
Problem with cyrillic project names

### ISSUE THREAD

**Issue by hastom** [dpa99c/cordova-plugin-firebase#18]
**Describe the bug**
When trying to build project with cyrillic name, building fails with error
```
ld: framework not found Pods_____
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I believe filename generates incorrectly because of extra underscores. And latin project name results in "Pods-Name" filename

**To Reproduce**

- Init test project with `cordova create test io.cordova.firebase.test`
- Setup plugin
- Change project name to something cyrillic like "Пепс"
- Make cordova "hard reset" `npx cordova platform rm ios && rm -rf plugins node_modules package-lock.json && npm install && npx cordova platform add ios && rm -rf ~/Library/Developer/Xcode/DerivedData/ && cordova prepare`

**Expected behavior**
App builds

**Screenshots**
![image](https://user-images.githubusercontent.com/11993866/60187809-e6d6bf00-9836-11e9-89bc-36c9d1b5a258.png)

**Plugin Version**
cordova-plugin-firebasex 3.0.5

**Comment by hastom** [comment]
Seems like cocoapods problem but not sure. They have similar issue with chinese symbols https://github.com/CocoaPods/CocoaPods/issues/8642

**Comment by dpa99c** [comment]
The cyrillic characters have made it through to the Xcode build, so this plugin is not at fault.

**Comment by deliverymanager** [comment]
Did you manage to solve this?
In my case it does not build is still searches for Pods________.framework

**Comment by Birowsky** [comment]
Any pointers, folks? Is there anything we may do by hand? In our build steps at least?

**Comment by deliverymanager** [comment]
The only thing I found was to use the localization plugin.

**Comment by Birowsky** [comment]
@deliverymanager  Wish I could upvote you more : )
