### ISSUE TITLE
Could not build module 'Firebase' on archiving Xcode project

### ISSUE THREAD

**Issue by tux240** [dpa99c/cordova-plugin-firebase#19]
Hello,

I have updated to cordova-ios 5.0.0 and this plugin to get android build successfully.
It works well, thanks. But, when I want to get an ios archive, I get this error on Xcode :

> Could not build module 'Firebase'

Do you have some tips ?

**Comment by dpa99c** [comment]
Did you open `YourProject.xcworkspace` or `YourProject.xcodeproj` in Xcode?
(you need to open `YourProject.xcworkspace` so both your Cordova app project and the Pods project will be loaded into Xcode.)

Have you [installed/updated Cocopods](https://github.com/dpa99c/cordova-plugin-firebase#cocoapods)?

Please try cloning and building [this example project](https://github.com/dpa99c/cordova-plugin-firebase-test) as a reference.

**Comment by tux240** [comment]
Thanks for your quickly answer it work !!
I had to open the .xcworkspace as you mention.

Thanks !!

**Comment by dpa99c** [comment]
👍  I've added a note to the documentation
