### ISSUE TITLE
Firebase Auth: Unexpected update behavior (iOS)

### ISSUE THREAD

**Issue by svzi** [dpa99c/cordova-plugin-firebase#20]
**Describe the bug**
As reported in some other issues here, I've updated from an older version of `cordova-plugin-firebase` to this plugin. Yesterday I was finally able to build my app on iOS again. So I've uploaded a new beta version to TestFlight. The new (internal) TestFlight beta has already been approved.

What keeps me concerned is the fact, that TestFlight doesn't allow me to **upgrade** my existing app (installed from the App Store). It only offers to **install** it, which means the current version gets replaced and data is lost!

The app I'm talking about, uses Firebase Auth to login users anonymously. With that UID it stores some data in the realtime database and FireStore. 

With this update, the user isn't logged in anymore. After installing the newest beta from TestFlight, all the data is lost. This is really a break, that I cannot afford. My (free) app has around 75.000 users. So if everyone loses his data, because of whatever the reason is, this is a deal breaker to me. 

**Plugin Version**
```
cordova-admob-plus 0.0.0 "@admob-plus/cordova"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-clipboard 1.2.1 "Clipboard"
cordova-ios-plugin-no-export-compliance 0.0.5 "iOS No Export Compliance"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-cocoapod-supportx 1.7.2 "Cordova CocoaPods Dependency Support"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-email-composer 0.9.2 "EmailComposer"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebasex 3.0.5 "Google Firebase Plugin"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic 5.3.0 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-purchase 8.1.1 "Purchase"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.7 "SocialSharing"
cordova-plugin-x-toast 2.7.2 "Toast"
es6-promise-plugin 4.2.2 "Promise"
```

**Smartphone (please complete the following information):**
Tested on an iPhone XR with iOS 12.2.

**Additional context**
I've also updated the `cordova-ios` platform with this update and some other cordova plugins as well.

Here are some additional informations:
```
 ~> ionic info

Ionic:

   Ionic CLI          : 5.0.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic 5.3.0, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 28 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.5

System:

   Android SDK Tools : 26.1.1 (/Users/svzi/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.1
   NodeJS            : v8.11.3 (/usr/local/bin/node)
   npm               : 5.6.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

Any help would be really much appreciated!

Cheers,
Sven

**Comment by dpa99c** [comment]
> With this update, the user isn't logged in anymore.

Is this because TestFlight forces you to re-install the app? (changes to this plugin cannot be the cause of that).

Or because you are now able to update the existing app but the new version of the Firebase SDK is not preserving the data from the previous installed version?

**Comment by svzi** [comment]
> Is this because TestFlight forces you to re-install the app? (changes to this plugin cannot be the cause of that).
> Or because you are now able to update the existing app but the new version of the Firebase SDK is not preserving the data from the previous installed version?

I simply don't know if this plugin could be the cause of it. I simply don't know what could be the cause of this mess in general and how to find the cause. 🤷🏼‍♂️

You're really sure that the changes to this plugin can not be the cause of it? Do you have any idea, what could be cause that TestFlight isn't serving the newest beta version as update? How can this happen? I thought it had something to do with the changes I made. For me it seems to be reasonable that some of the updated libs is causing this issue. But as I already stated, I have no clue...

**Comment by dpa99c** [comment]
Unlike Android (where APK is bytecode that can be inspected at upload by the Play Store), iOS apps are compiled C binaries which means there's no way that App Store Connect can inspect the contents to see what libs have changed/are present.

The most likely explanation for this is related to signing of the app.

I only experienced a situation like this once before when distributing iOS apps outside of the App Store via Enterprise distribution. In that case, the new version of the app had been signed with a different certificate than the installed one, so it was not possible to update.

Are you sure that you didn't have a development version installed on your device when trying to update it via TestFlight? 

I suggest carrying out this test:
- Delete existing app off device
- Install live version via App Store
- Run and sign in with Firebase
- Try to update via TestFlight

**Comment by svzi** [comment]
> The most likely explanation for this is related to signing of the app.
> I only experienced a situation like this once before when distributing iOS apps outside of the App Store via Enterprise distribution. In that case, the new version of the app had been signed with a different certificate than the installed one, so it was not possible to update.

😱

The provisioning profiles are only valid for one year, as far as I know. So I replaced the signing certificates as well. 🤦‍♂️

Under this circumstances does that mean when somebody creates new signing certificates for his iOS Firebase app with anonymous user, that all the user data is lost with a new version of the app? I can't believe that! 🤬

**Comment by dpa99c** [comment]
Your signing certificates are only used for validation by the App Store - when Apple publishes an iOS app in the App Store it resigns with their own distribution certificate.

That means even if your uploaded app is signed with a different certificate (because the old one expired), it won't matter because Apple will resign it when publishing to the App Store anyway.

I presume the same resigning must take place for TestFlight builds otherwise you wouldn't be able to update an app installed from the App Store (signed with Apple distribution cert) with one from TestFlight  unless it was signed with the same cert.

**Comment by svzi** [comment]
That's something I would assume as well, but then I don't get the point why my app isn't updatable via TestFlight (only install and replace the current installation and the anonymous user that is currently signed in). 🤔

**Comment by dpa99c** [comment]
Did you try my test steps above?

**Comment by svzi** [comment]
Yup, that were my exact steps. I removed the installed app. Did a fresh install and opened the app. Completed my "Welcome Wizard" and created some user content. Closed app, re-opened it. Everything was still in place, as expected. Started TestFlight and it's only showing "install" instead of "update". When I tap "install" TestFlight even warns me, that this will **replace** my existing installation and data could be lost! When I install it, all that is true. I will start again with the "Welcome Wizard" (which usually only appears on first start of the app) and my content is gone. 😢

**Comment by dpa99c** [comment]
Sounds like the issue is with App Store Connect/TestFlight - you should be able to update.

Try these things (in order):
- Uninstall/reinstall TestFlight app
- In App Store Connect, open your app page
	- Select TestFlight tab
    - Select Builds > iOS 
    - Select your build
    - Click "Expire build" button (top-right)
    - Build and upload a new build to App Store Connect

**Comment by svzi** [comment]
All done, except the new build is just uploading...

Just one question, do you have any experience with platforms like bitrise.io? I wonder if such kind of service would help me avoid such issues in the future...

**Comment by dpa99c** [comment]
I haven't encountered bitrise.io before but it seems like a new cloud build service.

I have had experience with others in the past: Phonegap Build and Telerik AppBuilder and I ended moving away from both back to a local build environment because they didn't give enough fine-grain control over the build.

My recommendation would be to stick with a local build environment if you are comfortable operating it. Remote cloud build services are OK if you lack the skills to setup your own local build environment but they come at the cost of flexibility and fine-grain control over your build process, not to mention debugging.

**Comment by svzi** [comment]
Thanks for your advice! I backed away from such kind of services the last couple of years as well. But this experience really let me re-think about all that stuff... At least bitrise.io is offering the ability to debug your project locally with the same settings (with there open sourced cli tools): https://discuss.bitrise.io/t/how-to-debug-your-build-locally-it-works-on-my-mac-pc-but-not-on-bitrise-io/392 

But I'm still not sold. Just hoped you had some good experience with it, because you quickly became someone I trust about such type of questions.

Btw, after removing my latest build from TestFlight, I figured out that my last beta (uploaded about 3 or 4 weeks ago) already served the initial issue of this topic. It's not updatable on the version I've installed from the App Store. So, even if you wouldn't have explained why your modifications could not be the reason, it would be clear that this issue has nothing todo with what you did. 

Good for you, but bad for me. Do you have any idea on how to fix this? If I would publish a new version, about 25.000 users of mine would lose their data. That's not acceptable, but not publishing any more updates to the app isn't acceptable as well. :-(

**Comment by dpa99c** [comment]
I'm out of ideas when it comes to this TestFlight update issue.
I would suggest that if searching Google and Stackoverflow comes up with nothing, you contact Apple tech support. After all, we pay our $99/year Apple Membership fee so should be able to tech support included with that! I'm pretty sure there's a way to ask this kind of question via App Store Connect...

**Comment by dpa99c** [comment]
I've just set a task for one of our junior devs to investigate bitrise.io and report back on whether they think it's any good. I'll let you know the result 😉

**Comment by svzi** [comment]
You're completely right about the Apple support. I've already had a call in the meanwhile. The person on the phone couldn't help me, but he will send me an email where I can reply with some further informations and screenshots, so he can forward it to someone with more knowledge in this topic.

Appreciate that you put on of your juniors devs on the bitrise investigation! Can't await to hear back about that topic. 👍
