### ISSUE TITLE
[iOS] Can't get the plugin working along with Google Analytics plugin

### ISSUE THREAD

**Issue by yosikal** [dpa99c/cordova-plugin-firebase#24]
Still using Google Analytics for my project as it has a lot of value for me. When trying to have both plugins installed I'm not able to build, the linker can't satisfy Google Analytics plugin dependencies. With the previous Firebase plugin that doesn't use cocoapods it is working.

**Comment by dpa99c** [comment]
[cordova-plugin-google-analytics](https://github.com/danwilson/google-analytics-plugin) depends on [`GoogleToolboxForMac v2.1.4`](https://github.com/danwilson/google-analytics-plugin/blob/master/plugin.xml#L51).

This plugin currently depends on Firebase SDK v6.3.0 which depends on `GoogleToolboxForMac v2.2.1`:


	Downloading dependencies
	Installing Crashlytics (3.12.0)
	Installing Fabric (1.9.0)
	Installing Firebase (6.3.0)
	Installing FirebaseABTesting (3.0.0)
	Installing FirebaseAnalytics (6.0.2)
	Installing FirebaseAnalyticsInterop (1.2.0)
	Installing FirebaseAuth (6.1.2)
	Installing FirebaseAuthInterop (1.0.0)
	Installing FirebaseCore (6.0.3)
	Installing FirebaseInstanceID (4.2.0)
	Installing FirebaseMessaging (4.1.0)
	Installing FirebasePerformance (3.1.0)
	Installing FirebaseRemoteConfig (4.1.0)
	Installing GTMSessionFetcher (1.2.2)
	Installing GoogleAppMeasurement (6.0.2)
	Installing GoogleToolboxForMac (2.2.1)
	Installing GoogleUtilities (6.2.0)
	Installing Protobuf (3.8.0)
	Installing nanopb (0.3.901)
	Generating Pods project


I suspect that version collision is the source of your error.
You'll need to fork (or locally modify) the `plugin.xml` of `cordova-plugin-google-analytics` to reference `GoogleToolboxForMac v2.2.1` so it aligns with this plugin.

Note: Google Analytics for mobile apps is deprecated and will Google Analytics will stop accepting data from mobile SDKs on 31 October so I strongly advise migration to Firebase Analytics or some other alternative.

**Comment by dpa99c** [comment]
Closed due to no response from OP
