### ISSUE TITLE
[iOS] Ensure $(inherited) flag is present in Xcode project build settings

### ISSUE THREAD

**Issue by dpa99c** [dpa99c/cordova-plugin-firebase#25]
Currently an iOS build outputs this warning:

	[!] The `FirebaseTest [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-FirebaseTest/Pods-FirebaseTest.debug.xcconfig'. This can lead to problems with the CocoaPods installation

	[!] The `FirebaseTest [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-FirebaseTest/Pods-FirebaseTest.release.xcconfig'. This can lead to problems with the CocoaPods installation

	    - Use the `$(inherited)` flag, or
	    - Remove the build settings from the target.
	    - Use the `$(inherited)` flag, or
	    - Remove the build settings from the target.

This can lead to iOS build issues (see #22).

So the plugin hook scripts need to ensure the `$(inherited)` flag is present in the LD_RUNPATH_SEARCH_PATHS field of the Xcode project build settings.

**Comment by dpa99c** [comment]
Fix published in `cordova-plugin-firebasex@3.0.7`

**Comment by sebastian-zarzycki-es** [comment]
FWIW I still see these warnings in 3.0.7.

**Comment by dpa99c** [comment]
you will see the warnings on `cordova platform add ios` because that's before the `after_prepare` script has run. 
But if you run `cordova prepare ios` or `cordova build ios` you won't see them, which is what matters.

**Comment by sebastian-zarzycki-es** [comment]
Ah. It's ok then, I guess. Thanks.

**Comment by consciousimages** [comment]
I actually see the warning in both places -  `cordova platform add ios` as well as `cordova build ios`, using version 6.0.2.
