### ISSUE TITLE
APK not building

### ISSUE THREAD

**Issue by robinflyhigh** [dpa99c/cordova-plugin-firebase#29]
**Describe the bug**
Not able to build apk after adding cordova-plugin-firebasex. Otherwise is is working.

**To Reproduce**
Steps to reproduce the behaviour:
1. In a new folder
2. ionic start conference
3. ionic cordova build android --verbose --info --stacktrace
4. ionic cordova plugin add cordova-plugin-firebasex
5. Check the error screenshot

**Expected behavior**
When we try to build the apk with just the base ionic conference template the apk is building

**Screenshots**
Error: https://i.imgur.com/Lm8LqLO.jpg
Ionic Info: https://i.imgur.com/W3r3VrB.png
Plugin List: https://i.imgur.com/DFKQLZ6.png

[config-package.zip](https://github.com/dpa99c/cordova-plugin-firebase/files/3350466/config-package.zip)

**Comment by dpa99c** [comment]
The error screenshot indicates that a plugin (`cordova-plugin-ionic-webview`) in the project is referencing the legacy Android Support Library which is incompatible with its successor - AndroidX.
To resolve this, [as documented](https://github.com/dpa99c/cordova-plugin-firebase#androidx), add [cordova-plugin-androidx-adapter](https://github.com/dpa99c/cordova-plugin-androidx-adapter) to the project to dynamically migrate plugin code from the Support Library to AndroidX:

    cordova plugin add cordova-plugin-androidx-adapter

**Comment by robinflyhigh** [comment]
Works, sorry about this.

I got confused with cordova-plugin-androidx & cordova-plugin-androidx-adapter.

Thanks
