### ISSUE TITLE
cordova-plugin-cocoapod-support dependency not found

### ISSUE THREAD

**Issue by alexarvanitidisalpha** [dpa99c/cordova-plugin-firebase#3]
**Describe the bug**
Hi Dave,

You're saving the world today, thank you for your support and your plugins! I believe so many people are facing the same firebase issues right now and cannot release their app.

We have 2 issues on our repo (we're using Ionic, when running `ionic cordova platform add android@8.0.0`, the same issue happens on ios), the dependencies cannot be found

**Console output** 
```
Failed to install 'cordova-plugin-firebase': CordovaError: Failed to fetch plugin https://github.com/dpa99c/cordova-plugin-cocoapods-support.git via registry.
```
and the same for the cocoapods dependency of your firebase fork:
```
Failed to install 'cordova-plugin-firebase': CordovaError: Failed to fetch plugin https://github.com/dpa99c/cordova-plugin-cocoapods-support.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
TypeError: Parameter "url" must be a string, not undefined
    at [...]/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:161:37
    at _rejected ([...]/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at [...]/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when ([...]/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch ([...]/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at [...]/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle ([...]/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush ([...]/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Failed to fetch plugin https://github.com/dpa99c/cordova-plugin-cocoapods-support.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
```

**Plugin Version**
runbning `cordova plugin list`:
cordova-fabric-plugin 1.1.14-dev "cordova-fabric-plugin"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebase 2.0.5-custom "Google Firebase Plugin"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.0 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-pincheck 0.0.6 "PinCheck"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

**Additional context**
Thanks for your effort, hope it's not something we have configured incorrectly on our Jfrog. Could it be that your forks are not public or smth?

**Comment by dpa99c** [comment]
The repo is public: https://github.com/dpa99c/cordova-plugin-cocoapods-support.git

And it's a string: https://github.com/dpa99c/cordova-plugin-firebase/blob/master/plugin.xml#L9

It works fine in my test build (see console output): https://github.com/arnesson/cordova-plugin-firebase/issues/1081#issuecomment-503135862

Please try the commands in that test scenario.

**Comment by dann95** [comment]
Same problem here:
```
Adding cordova-plugin-media to package.json
Saved plugin info for "cordova-plugin-media" to config.xml
Discovered plugin "cordova-plugin-firebase" in config.xml. Adding it to the project
Installing "cordova-plugin-firebase" for android
Failed to install 'cordova-plugin-firebase': CordovaError: Failed to fetch plugin https://github.com/dpa99c/cordova-plugin-cocoapods-support.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:161:37
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

thats really weird, cause yesterday worked fine, today im having this problem too, in Jenkins container and my pc..

**Comment by dann95** [comment]
![image](https://user-images.githubusercontent.com/9970959/59786436-a1961880-929d-11e9-8f01-7a165a202fef.png)

**Comment by dann95** [comment]
Really weird, using a fork (in my profile) from cordova-plugin-cocoapod-support i get the same error, but removing the git URL, to fetch from NPM, seems normal ._.

**Comment by dpa99c** [comment]
I've patch my fork of cordova-plugin-cocoapods-support to work with cordova@9 so I don't really want to switch it back to the official npm release.

Probably the easiest thing is if I publish the plugin to npm under a different ID - Cordova seems happier if the plugin comes from npm rather than git.

**Comment by dann95** [comment]
@dpa99c idk so much about you, i only know that you saved my life two times XD, so i trust you yeah.., seems great create a npm repo, and set a different cordova plugin ID, it gives you the ability to release different tags, and keep version stable in config.xml, cause when we point to "git", it uses the master, and the last commit..

**Comment by dann95** [comment]
maybe thats a good point also to the cordova-plugin-firebase, have a different id instead of considering this a fork.. the official repo takes a long time to merge fixes, and alaways is having braking changes/deprecation's, so i think is a nice solution..

**Comment by dpa99c** [comment]
> maybe thats a good point also to the cordova-plugin-firebase, have a different id instead of considering this a fork.. the official repo takes a long time to merge fixes, and alaways is having braking changes/deprecation's, so i think is a nice solution..

good idea - will publish this one too under a different ID

**Comment by dpa99c** [comment]
You should now be able to do:

    cordova plugin add cordova-plugin-androidx

which will pull in `cordova-plugin-cocoapod-supportx`

**Comment by dann95** [comment]
testing!

**Comment by dann95** [comment]
working fine, i guess o refer to:
```
cordova plugin add cordova-plugin-firebasex
```

**Comment by dpa99c** [comment]
guess we can close this then?

**Comment by dann95** [comment]
ofc, thanks again, and if game were a game, you unlocked an achievement, now you'r "Hero of my project" hahahahaha

**Comment by dpa99c** [comment]
😁 😁
