### ISSUE TITLE
iOS build failing (cocoapods)

### ISSUE THREAD

**Issue by mbunby** [dpa99c/cordova-plugin-firebase#35]
**Describe the bug**
ios build fails as the build tools cannot find/build the frameworks installed via cocoapods.

**To Reproduce**
this is restoring a platform after removing the plugins, platforms and node_modules directories.

`cordova prepare ios`
<img width="1636" alt="Screenshot 2019-07-05 at 11 47 43" src="https://user-images.githubusercontent.com/6496127/60717766-be2b8500-9f1a-11e9-8841-36ad1f38ebad.png">
it looks like it has installed the plugin correctly.

but when it runs the podify.js hook 'after_prepare' it hasn't found any pods to install. if i cd into the xcode project dir and run `pod install` manually, still cannot find them as the pod file is still empty.
<img width="1637" alt="Screenshot 2019-07-05 at 11 51 07" src="https://user-images.githubusercontent.com/6496127/60717971-47db5280-9f1b-11e9-877d-4efee5d1d518.png">

if i run `cordova prepare ios` a second time, podify.js does find the pods and installs them.
<img width="1078" alt="Screenshot 2019-07-05 at 12 16 32" src="https://user-images.githubusercontent.com/6496127/60719169-bf5eb100-9f1e-11e9-9b95-18d0abd12bd0.png">

then, when i try to build `cordova run ios --noprepare --device --debug` it looks like it errors trying to use the dependencies of the dependencies listed in the pod file.
<img width="1637" alt="Screenshot 2019-07-05 at 12 22 39" src="https://user-images.githubusercontent.com/6496127/60719452-9d196300-9f1f-11e9-9b36-a11fcd56065e.png">

but looking back through the console log...
<img width="1639" alt="Screenshot 2019-07-05 at 12 24 44" src="https://user-images.githubusercontent.com/6496127/60719528-e5388580-9f1f-11e9-9fb2-17d6c31dd821.png">
the linker cannot find any of the frameworks. i checked those paths in 'DerivedData' dir and there is nothing there. interestingly, the path to the xcode project pod dir has a nested '/Pods/' that isn't meant to be there. e.g. `/platforms/ios/Pods/Pods/Crashlytics/iOS`.

i hope someone can point me in the right direction where it's going wrong. i've been looking at this for a couple of days now and i'm stumped. any help is greatly appreciated.

for android, it works totally fine!

**Expected behavior**
install plugin and setup/install pod file dependencies after the first time run `cordova prepare ios`, so ios app builds successfully.

**Plugin Version**
cordova-plugin-firebasex 3.0.8 "Google Firebase Plugin"

other stuff:
xcode 10.1
cordova 8.0 & 9.0 
cordova-ios 4.3.1
node 8.12.0
npm 6.4.1

**Comment by dpa99c** [comment]
I suggest cloning and trying to build [this example project](https://github.com/dpa99c/cordova-plugin-firebase-test). 
It builds and runs fine in my (and other dev's) environments so you should be able to use it to validate your build environment. If that works OK, then it's likely to be something specific in your other project causing the issue e.g. a conflict with another plugin.

**Comment by mbunby** [comment]
i tried building your example project, but it failed to build through the cli for some reason - unrelated to this issue though. it did build in xcode, and so does my project, as it turns out.

since we were using an old version of cordova-ios, i figured i'd try out the latest version of it (5.0.1). using the latest version works. not sure if anyone else has had success building with cordova-ios 4.3.1? is anyone even using that version anymore? we still need ios 8 support, unfortunately. so we can't update to the latest version just yet.

looks like the plugin is all good!

i just want to say thanks for replying and for maintaining this plugin. it really helped us out getting our android build working again 👍

**Comment by dpa99c** [comment]
There is an outstanding issue with building iOS from the CLI: https://github.com/dpa99c/cordova-plugin-firebase/issues/22
I hope to be able to resolve it while retaining the ability to support user-overridable versions for the Firebase SDK component version on iOS.
