### ISSUE TITLE
Android build error: failed linking references

### ISSUE THREAD

**Issue by tux240** [dpa99c/cordova-plugin-firebase#37]
Hello,

I have installed this plugin with cordova-plugin-androidx-adapter.
IO also installed this plugins : 
- cordova-android-firebase-gradle-release
- cordova-android-play-services-gradle-release
- cordova-android-support-gradle-release

Now, when I'm trying to build an android version, I get this error 👍 

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugResources'.
> > Android resource linking failed
>   /Users/matthieupoulin/Sources/utily-platform/mobile/platforms/android/app/src/main/res/values/strings.xml: AAPT: error: resource string/Utily (aka com.utily.staging:string/Utily) not found.

Do you already get this kind of error ?

Thanks for your help.

**Comment by dpa99c** [comment]
`resource string/Utily (aka com.utily.staging:string/Utily) not found.`

This error is not related to this plugin.

Please build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebase) to verify this plugin works correctly and use it as a working reference to diagnose the build issues in your own project.
