### ISSUE TITLE
firebase vs firebasex vs firebase-lib ....?

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-plugin-firebase#39]
Dave, can you comment on this thread I posted over on `firebase-lib` please. https://github.com/wizpanda/cordova-plugin-firebase-lib/issues/39#issuecomment-509739643
 Looks like we have 3 forks now, orig I am told is not being maintained while yours is a working/maintained fork while `firebase-lib` is a fork that IS being maintained.  Can these be merged?

**Comment by dpa99c** [comment]
I'm in the process of rewriting parts of this plugin from the ground up as you can see on the [dev branch](https://github.com/dpa99c/cordova-plugin-firebase/tree/dev) e.g. [reworking of Cloud Messaging](https://github.com/dpa99c/cordova-plugin-firebase/commit/e1fa4f2d0cf21785d7e3c8ab7ca36d4f05206a1c) to fully support all Firebase options (I'm using the [dev branch of the example project](https://github.com/dpa99c/cordova-plugin-firebase-test/tree/dev) as a test harness for validation). 

Once my rewrite is complete (it's for my own purposes to be used in production apps) then I'd be happy to merge the changes back to `cordova-plugin-firebase` or `cordova-plugin-firebase-lib` and have someone else maintain them - I have enough Cordova plugins to maintain as it is!

But until that point I will continue development on this fork and it's up to you if you want to use it or another fork.

Hope that is sufficient explanation.

**Comment by rolinger** [comment]
It is....thx.
