### ISSUE TITLE
Can't build with cordova-plugin-camera plugin

### ISSUE THREAD

**Issue by dassram17** [dpa99c/cordova-plugin-firebase#41]
**Describe the bug**
i'm using both firebasex and camera@4.1.0 plugin.. it shows following error

---------------------------------------------------------------------------
> Task :app:createDebugCompatibleScreenManifests

> Task :app:processDebugManifest
E:\xampp\htdocs\dd\platforms\android\app\src\main\AndroidManifest.xml:24:9-31:50 Warning:
        activity#com.google.firebase.auth.internal.FederatedSignInActivity@android:launchMode was tagged at AndroidManifest.xml:24 to replace other declarations but no other declaration present

> Task :app:fabricGenerateResourcesDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:mergeDebugResources
> Task :app:processDebugResources

> Task :app:compileDebugJavaWithJavac FAILED
33 actionable tasks: 10 executed, 23 up-to-date
E:\xampp\htdocs\dd\platforms\android\app\src\main\java\org\apache\cordova\camera\CameraLauncher.java:40: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
                                 ^
E:\xampp\htdocs\dd\platforms\android\app\src\main\java\org\apache\cordova\camera\CordovaUri.java:25: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
                                 ^
E:\xampp\htdocs\dd\platforms\android\app\src\main\java\org\apache\cordova\camera\FileProvider.java:21: error: package android.support.v4.content does not exist
public class FileProvider extends android.support.v4.content.FileProvider {}
                                                            ^
E:\xampp\htdocs\dd\platforms\android\app\src\main\java\org\apache\cordova\camera\CameraLauncher.java:303: error: cannot find symbol
        this.imageUri = new CordovaUri(FileProvider.getUriForFile(cordova.getActivity(),
                                                   ^
  symbol:   method getUriForFile(Activity,String,File)
  location: class FileProvider
E:\xampp\htdocs\dd\platforms\android\app\src\main\java\org\apache\cordova\camera\CameraLauncher.java:801: error: cannot find symbol
                        Uri tmpFile = FileProvider.getUriForFile(cordova.getActivity(),
                                                  ^
  symbol:   method getUriForFile(Activity,String,File)
  location: class FileProvider
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
E:\xampp\htdocs\dd\platforms\android\gradlew: Command failed with exit code 1 Error output:
E:\xampp\htdocs\dd\platforms\android\app\src\main\java\org\apache\cordova\camera\CameraLauncher.java:40: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
                                 ^
E:\xampp\htdocs\dd\platforms\android\app\src\main\java\org\apache\cordova\camera\CordovaUri.java:25: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
                                 ^
E:\xampp\htdocs\dd\platforms\android\app\src\main\java\org\apache\cordova\camera\FileProvider.java:21: error: package android.support.v4.content does not exist
public class FileProvider extends android.support.v4.content.FileProvider {}
                                                            ^
E:\xampp\htdocs\dd\platforms\android\app\src\main\java\org\apache\cordova\camera\CameraLauncher.java:303: error: cannot find symbol
        this.imageUri = new CordovaUri(FileProvider.getUriForFile(cordova.getActivity(),
                                                   ^
  symbol:   method getUriForFile(Activity,String,File)
  location: class FileProvider
E:\xampp\htdocs\dd\platforms\android\app\src\main\java\org\apache\cordova\camera\CameraLauncher.java:801: error: cannot find symbol
                        Uri tmpFile = FileProvider.getUriForFile(cordova.getActivity(),
                                                  ^
  symbol:   method getUriForFile(Activity,String,File)
  location: class FileProvider
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
------------------------

android platform@8.0.0
cordova platform@9.0.0
android studio version@3.4.2

**Comment by dpa99c** [comment]
The same cause as #29 - `cordova-plugin-camera` references the legacy Android Support Library so you need to add [cordova-plugin-androidx-adapter](https://github.com/dpa99c/cordova-plugin-androidx-adapter) to your project to patch it:

    cordova plugin add cordova-plugin-androidx-adapter

**Comment by dassram17** [comment]
> The same cause as #29 - `cordova-plugin-camera` references the legacy Android Support Library so you need to add [cordova-plugin-androidx-adapter](https://github.com/dpa99c/cordova-plugin-androidx-adapter) to your project to patch it:
> 
> ```
> cordova plugin add cordova-plugin-androidx-adapter
> ```

Thanks a lot man.. It works great...

**Comment by yuanzuo** [comment]
I installed cordova-plugin-androidx-adapter, but I still got android build error: error: package android.support.v4.content does not exist. Any ideas?

**Comment by dassram17** [comment]
> I installed cordova-plugin-androidx-adapter, but I still got android build error: error: package android.support.v4.content does not exist. Any ideas?

whats your android platform version?

**Comment by yuanzuo** [comment]
>cordova -v
8.0.0



>cordova platform ls
Installed platforms:
android 8.0.0



    On Wednesday, July 31, 2019, 02:50:52 AM EDT, dassram17 <notifications@github.com> wrote:  
 
 

I installed cordova-plugin-androidx-adapter, but I still got android build error: error: package android.support.v4.content does not exist. Any ideas?


whats your android platform version?

**Comment by yuanzuo** [comment]
I opened a new issue in #69

**Comment by kleeb** [comment]
cordova-plugin-androidx-adapter is a dependency, so if its not added it means that there is some error (like for instance missing deps, it uses couple npm modules like recursive-readdir, xml-js, performance-now, ...)

check the logs

**Comment by prabhashibuddhima** [comment]
> The same cause as #29 - `cordova-plugin-camera` references the legacy Android Support Library so you need to add [cordova-plugin-androidx-adapter](https://github.com/dpa99c/cordova-plugin-androidx-adapter) to your project to patch it:
> 
> ```
> cordova plugin add cordova-plugin-androidx-adapter
> ```

Thanks a lot!! saved my day!

**Comment by re-beat** [comment]
Thaks a lot guys

**Comment by zimejin** [comment]
> The same cause as #29 - `cordova-plugin-camera` references the legacy Android Support Library so you need to add [cordova-plugin-androidx-adapter](https://github.com/dpa99c/cordova-plugin-androidx-adapter) to your project to patch it:
> 
> ```
> cordova plugin add cordova-plugin-androidx-adapter
> ```

This resolved the issue completely. Thank you so much.

**Comment by fouzo09** [comment]
> > I installed cordova-plugin-androidx-adapter, but I still got android build error: error: package android.support.v4.content does not exist. Any ideas?
> 
> whats your android platform version?



> The same cause as #29 - `cordova-plugin-camera` references the legacy Android Support Library so you need to add [cordova-plugin-androidx-adapter](https://github.com/dpa99c/cordova-plugin-androidx-adapter) to your project to patch it:
> 
> ```
> cordova plugin add cordova-plugin-androidx-adapter
> ```

Thank you it's work for me
