### ISSUE TITLE
Consider upgrade to more recent iOS lib

### ISSUE THREAD

**Issue by yosikal** [dpa99c/cordova-plugin-firebase#8]
Current plugin.xml spec points to version 5.15 which was released in December, 2018. There were few releases since than that included fixing issues causing crash on iOS. For example, see this issue which was fixed in releases in the last couple of months: https://github.com/firebase/firebase-ios-sdk/issues/2019

**Comment by dpa99c** [comment]
Yep, updating the pinned versions is on my TODO list.

But I'm also working on a mechanism by which you can override the default versions specified in the plugin using plugin variables so you can take control of dependency versioning for both Android & iOS.
Hope to release it in the next couple of days.

**Comment by dpa99c** [comment]
I just published `cordova-plugin-firebasex@3.0.1` to npm which bumps the default Firebase SDK version on iOS to v5.20.2

v3.x of this plugin now enables you to override the defaults using plugin variables, e.g.:

    cordova plugin add cordova-plugin-firebasex \
        --variable ANDROID_PLAY_SERVICES_TAGMANAGER_VERSION=17.0.0 \
        --variable ANDROID_FIREBASE_CORE_VERSION=17.0.0 \
        --variable ANDROID_FIREBASE_MESSAGING_VERSION=19.0.0 \
        --variable ANDROID_FIREBASE_CONFIG_VERSION=18.0.0 \
        --variable ANDROID_FIREBASE_PERF_VERSION=18.0.0 \
        --variable ANDROID_FIREBASE_AUTH_VERSION=18.0.0 \
        --variable ANDROID_CRASHLYTICS_VERSION=2.9.8 \
        --variable ANDROID_SHORTCUTBADGER_VERSION=1.1.22 \
        --variable IOS_FIREBASE_CORE_VERSION=5.20.2 \
        --variable IOS_FIREBASE_AUTH_VERSION=5.20.2 \
        --variable IOS_FIREBASE_MESSAGING_VERSION=5.20.2 \
        --variable IOS_FIREBASE_PERFORMANCE_VERSION=5.20.2 \
        --variable IOS_FIREBASE_REMOTECONFIG_VERSION=5.20.2 \
        --variable IOS_FABRIC_VERSION=1.9.0 \
        --variable IOS_CRASHLYTICS_VERSION=3.12.0
